config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :accounts, controllers: { sessions: 'accounts/sessions' }
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :blog_posts do
    collection do
      get "new_blog"
      post "create_blog"
      get "sort_blogs"
    end
  end
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :account

  validates :title, presence: true
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  def index
    @blog_posts = BlogPost.joins(:account).all
    respond_to do |format|
      format.html
    end
  end

  def new
    @blog_post = BlogPost.new
  end

  def create_blog
    @blog_post = BlogPost.new(blog_post_params)
    if @blog_post.save
      respond_to do |format|
        format.json {render json: 'success'}
      end
    else
      respond_to do |format|
        format.json {render json: 'failed'}
      end
    end
  end

  def show_blog
    @blog_post = BlogPost.find_by_id(params[:id])
  end

  def new_blog
    respond_to do |format|
      format.html { render layout: false }
    end
  end

  def sort_blogs
    @blog_posts = BlogPost.joins(:account).order("created_at #{params[:sort]}")
    render json: @blog_posts.collect{
      |x| [x.id, x.title, x.content, x.account.full_name,
        x.created_at.strftime('%d-%b-%Y %H:%M')]}
  end

  def edit
    @blog_post = BlogPost.find_by_id(params[:id])
  end

  private
    def blog_post_params
      params.require(:blog_post).permit(:title, :content, :account_id)
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/index.html.erb
<div class="blog-wrapper clearfix">
  <div class="blog-tools clearfix">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix padding-0">
      <div style="height:35px; line-height:35px;">
        <a href="#" class="sort-btn checkbox-styled"></a>
        <span class="filter-text">Sort Blog Posts</span>
      </div>
      <input type="text" class="text-filter txt-cls-deco" placeholder="Type here to filter blog posts" />
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 clearfix padding-0">

    </div>
  </div>
  <ul class="blog-content clearfix">
    <li class="blog-head-bar title">Blog Title</li>
    <li class="blog-head-bar author">Author Info</li>
    <% if @blog_posts.length > 0 %>
      <% @blog_posts.each do |f| %>
        <li class="title">
          <a href="/blog_posts/<%= f.id%>">
            <%= "#{f.title.truncate(30)} (#{f.created_at.strftime('%d-%b-%Y %H:%M')})" %>
          </a>
        </li>
        <li class="author-detail">
          <%= f.account.full_name %>
        </li>
      <% end %>
    <% else %>
      <li>There are no existing blog! </li>
    <% end %>
    <hr />
    <% unless current_account.nil? %>
      <a href="#" class="btn-new-blog new-blog-deco clearfix">Create new blog</a>
    <% end %>
  </ul>
</div>

app/views/blog_posts/new_blog.html.erb
<%= form_for :blog_post, method: 'post', html: { class: 'blog-form clearfix padding-0'},
  url: '/blog_posts' do |f| %>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <h3>Title</h3>
      <%= f.text_field :title %>
      <h3>Content</h3>
      <div id="wysihtml5-toolbar" style="display: none;" class="clearfix">
        <a data-wysihtml5-command="bold">bold</a>
        <a data-wysihtml5-command="italic">italic</a>
        <a data-wysihtml5-command="underline">underline</a>
        <a data-wysihtml5-command="insertImage">insert image</a>
        <div data-wysihtml5-dialog="insertImage" style="display: none;">
          <label>
            Image:
            <input data-wysihtml5-dialog-field="src" value="http://">
          </label>
          <label>
            <a data-wysihtml5-dialog-action="save">OK</a>
            <a data-wysihtml5-dialog-action="cancel">Cancel</a>
          </label>
        </div>

        <a data-wysihtml5-command="insertOrderedList">insert ordered list</a>
        <a data-wysihtml5-command="insertUnorderedList">
          insert unordered list</a>

        <a data-wysihtml5-command="foreColor"
          data-wysihtml5-command-value="red">red</a>
        <a data-wysihtml5-command="foreColor"
          data-wysihtml5-command-value="green">green</a>
        <a data-wysihtml5-command="foreColor"
          data-wysihtml5-command-value="blue">blue</a>

        <a data-wysihtml5-command="createLink">insert link</a>
        <div data-wysihtml5-dialog="createLink" style="display: none;">
          <label>
            Link:
            <input data-wysihtml5-dialog-field="href"
              value="http://" class="text">
          </label>
          <a data-wysihtml5-dialog-action="save">OK</a>
          <a data-wysihtml5-dialog-action="cancel">Cancel</a>
        </div>
      </div>
      <%= f.text_area :content, id: 'wysihtml5-textarea', class: 'blog-content-style'  %>
      <%= f.hidden_field :account_id, value: current_account.id %>
      <%= f.button "Create" %>
    </div>
<% end %>
<br />
<script>
  var wysihtml5ParserRules = {
    tags: {
      "img": {
        "check_attributes": {
          "width": "numbers",
          "alt": "alt",
          "src": "url",
          "height": "numbers"
        }
      }
    }
  };
  var editor = new wysihtml5.Editor("wysihtml5-textarea", {
    toolbar:      "wysihtml5-toolbar",
    stylesheets:  "<%= stylesheet_path('wysiwyg') %>",
    parserRules:  wysihtml5ParserRules,
  });
</script>